# server.servlet.context-path = /todo_app/v1
server:
#  servlet:
#    context-path: /api/v1
  port: 9080

spring:
  application:
    name: template-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3308/street57
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none