# server.servlet.context-path = /todo_app/v1
server:
#  servlet:
#    context-path: /api/v1
  port: 9080

spring:
  application:
    name: template-app
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: "jdbc:h2:mem:reproduccionapp;"
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  jersey:
    type:filter
